"""Added date column

Revision ID: 025301b1a1f1
Revises: 
Create Date: 2023-11-02 08:58:13.514390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025301b1a1f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
