"""changed password_hash type

Revision ID: a5cf77c502c9
Revises: 1fd80cc9436a
Create Date: 2023-12-21 11:57:06.162424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5cf77c502c9'
down_revision = '1fd80cc9436a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.alter_column('password_hash',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.LargeBinary(),
    #            existing_nullable=False)

    op.execute('ALTER TABLE "user" ALTER COLUMN password_hash TYPE bytea USING password_hash::bytea')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
